export const meta = {
  name: 'tairyo-prepublish-review',
  description: 'Pre-publish review of the Tairyo Kaiten Sushi site: 4 independent reviewers (code/a11y/responsive, facts vs sources, ES+EN copy, export/SEO/deploy), every finding checked by 2 skeptics',
  phases: [
    { title: 'Review', detail: '4 reviewers, one dimension each' },
    { title: 'Verify', detail: '2 independent skeptics per finding' },
  ],
}

const ROOT = 'C:/Users/dopelganger/Documents/Ресттораны/tairyo-kaiten-sushi'
const URL_ES = 'http://localhost:4471/tairyo-kaiten-sushi/'
const URL_EN = 'http://localhost:4471/tairyo-kaiten-sushi/en/'
const COMMON = `Project: ${ROOT} — Next.js 16 static-export bilingual landing (ES at /, EN at /en/) for Tairyo Kaiten Sushi Valencia, a conveyor-belt ("kaiten") all-you-can-eat sushi buffet where miniature trains on an upper rail bring drinks and à la carte orders. Read ${ROOT}/DESIGN.md first (sources, decisions, tokens). Data lives in lib/ (restaurant.ts, menu.ts [GENERATED by scripts/build-menu.mjs], reviews.ts, photos.ts, dictionaries.ts); components in components/; styles app/globals.css. Raw sources in ${ROOT}/_data: maps/place-parsed.json and maps/place-es.txt (Google place payload; JSON after the first line; j[6]), maps/raw/reviews-es-newest.json + reviews-en-relevant.json (400 Google reviews), maps/ig/*.json (Instagram captions) + maps/ig/precios-post.jpg, menu-text/menu-final.json (reconciled carta transcription) + menu-text/translate-en-final.json, web/*.html (their website pages: inicio-valencia, historia-valencia, buffet-giratorio-valencia, contacto-valencia), web/carta/pdf/p1..p9.png (their PDF menu pages), photo-sheets/catalog-all.json (catalogue of 495 Google photos), photos/orig/*.jpg and ${ROOT}/_photos/*.jpg (photos used on the site).
The production build (basePath /tairyo-kaiten-sushi) is served statically at ${URL_ES} (ES) and ${URL_EN} (EN) — a copy of out/; rebuilds do not change it. For screenshots: cd ${ROOT}/_data/scripts && PORT=<your port> node shoot.mjs <url> <width> <outPrefix> [chunk=1800] [scale=1] — prints {sw,cw,h,hidden reveals,overflow,broken images}; writes JPEG chunks; save outputs under ${ROOT}/_data/crops/review-<you>-*. Menu tab behaviour test: node test-tabs.mjs <url> 375. Do NOT edit any project file — report only.
Report concrete, verifiable defects (file + line, what is wrong, why it matters, the fix). Do not report style preferences or things DESIGN.md already decided deliberately. Past houses in this folder had these real bugs — check them here too: whileInView reveals staying invisible on short screens; sr-only on <table> widening the page; header controls overflowing at 320–364 px; focus ring invisible on same-colour backgrounds (here: red CTA band, red header button, ink sections); scroll-padding-top + scroll-mt doubling; sticky tab strip needing overflow-x-clip; hero rendered with SSR opacity:0; aria-label not starting with the visible label (label-in-name); mobile menu staying inert after resize to xl; hydration mismatches in time-dependent client components (Prices "now" chip, HoursTable status, Busy default day); JSON-LD aggregateRating (self-serving); OG image as WebP; 404 missing on Pages with two root layouts; SVG pattern ids duplicated on one page; continuous animation without a pause control.
FINALLY: save your findings as JSON with the Write tool to ${ROOT}/_data/crops/review-findings-<your dimension key>.json, then return the structured object.`

const DIMENSIONS = [
  {
    key: 'code-a11y',
    port: 9621,
    prompt: `${COMMON}

Your dimension key: code-a11y. CODE CORRECTNESS, ACCESSIBILITY and RESPONSIVE LAYOUT. Read every component and lib file. Check: semantics and heading order (h1 → h2 → h3 per section, incl. the menu groups), the menu tablist (MenuTabs.tsx) keyboard behaviour and ARIA, the conveyor band (Cinta.tsx: decorative, pause button, reduced motion), the Busy chart day buttons, the Prices tariff logic for every day/time (madridNow in Prices.tsx: Mon–Fri lunch 20.95; Mon–Thu dinner 23.95; Fri dinner + Sat/Sun all day 26.95; after 23:30 → next day's lunch) and HoursTable status logic (two shifts per day), focus visibility on every tone (light/deep/dark/red), contrast of every text/background pair actually used (compute it; tokens are in globals.css), touch targets ≥44px, images (alt, width/height matching the files in public/photos, sizes), hydration mismatches, reduced motion (REDUCED=1 env in shoot.mjs), the logo masks (Logo.tsx; public/brand/*.webp), layout at 320, 375, 768, 1024, 1440 px (screenshot with shoot.mjs using PORT=9621; check sw vs cw; the menu tab strip scrolls horizontally by design; the cinta track overflows inside its overflow-hidden band by design), and anything that would break in production. Also test the EN page.`,
  },
  {
    key: 'facts',
    port: 9622,
    prompt: `${COMMON}

Your dimension key: facts. FACTUAL ACCURACY of every claim on the site against the raw sources. Go through lib/restaurant.ts, lib/dictionaries.ts (ES and EN), lib/reviews.ts, lib/photos.ts (alt texts vs what the photos in ${ROOT}/_photos/ show — Read the images), components with hard-coded text, JSON-LD (components/JsonLd.tsx) and metadata (lib/site.ts). For each claim find the source (quote it) or flag it as unsupported/overstated/contradicted. Specifically verify: hours (13:00–16:30 and 20:00–23:30 every day; the carta says 20:00–00:00 — see DESIGN.md §2.5), address/postcode/district, phone 666 25 63 50, e-mail, rating 4.4/400, histogram, topics and counts (j[6][175], j[6][153]), popular-times arrays vs payload j[6][84] (day 1 = Monday … 7 = Sunday), attributes (j[6][100]), buffet prices and rules (run: npm run check:menu; compare with web/carta/pdf/p2.png and maps/ig/precios-post.jpg), "trains bring drinks and à la carte orders" (Instagram DdFDcVdIvYQ + reviews), "cada plato tiene su número", "a un par de calles del Mercado de Colón" (compute distance from 39.4675,-0.3696 to Mercado de Colón), "se entra por una rampa… abajo, la sala", "un shinkansen blanco, una locomotora de vapor negra y hasta un camión", "kokeshi gigante", the Osaka history paragraph vs web/historia-valencia.html, review texts/authors/months vs the raw review files (scraped 18–19.09.2026; month = scrape date minus the relative time), photo captions in dictionaries (carta.photoCaptions, how.*Caption, hero.caption), and anything else that states a fact.`,
  },
  {
    key: 'copy',
    port: 9623,
    prompt: `${COMMON}

Your dimension key: copy. LANGUAGE QUALITY of both locales. Spanish: natural Spain-Spanish, correct accents/punctuation (¿¡, «», —), consistent terms (buffet vs bufé, carta vs menú), no calques. English: natural British English, faithful to the Spanish (no added claims), consistent terms (belt, bullet train, menu), correct € formatting from lib/format.ts, day names, 24h times. Check every string in lib/dictionaries.ts, lib/menu.ts (dish names/descriptions both languages — the ES text is the restaurant's own; only obvious typos were fixed via FIXES in scripts/build-menu.mjs; judge the EN translations), lib/photos.ts alts, components' literal strings, metadata titles/descriptions (length ok for SEO?), and the 404 page (out/404.html in _data/serve). Also look at the rendered pages (screenshots with shoot.mjs PORT=9623 at 1440 and 375) for awkward line breaks, orphaned words in headings, overflowing labels, mixed languages on the EN page.`,
  },
  {
    key: 'export-seo',
    port: 9624,
    prompt: `${COMMON}

Your dimension key: export-seo. STATIC EXPORT, GITHUB PAGES DEPLOY, SEO and PERFORMANCE. The served copy at ${ROOT}/_data/serve was built exactly as CI will (NEXT_PUBLIC_BASE_PATH=/tairyo-kaiten-sushi) but WITHOUT NEXT_PUBLIC_SITE_URL; to check absolute URLs, copy the project to a scratch folder (tar -C ${ROOT} --exclude=node_modules --exclude=.next --exclude=out --exclude=_data --exclude=_photos -cf - . | tar -C <scratch>/t -xf - ; then copy node_modules) and build there with (Git Bash) MSYS_NO_PATHCONV=1 NEXT_PUBLIC_BASE_PATH=/tairyo-kaiten-sushi NEXT_PUBLIC_SITE_URL=https://slonikonclaude.github.io npm run build. Inspect out/: every asset URL prefixed with /tairyo-kaiten-sushi (html, css url(), srcset, the --mask CSS variables of the logo masks, og:image, icons, JSON-LD urls), 404.html exists and renders, /en/index.html, hreflang/canonical/alternates correct and absolute, og.jpg is JPEG 1200×630, title/description lengths, JSON-LD validity (Restaurant, no aggregateRating, openingHoursSpecification with two shifts), lang attributes, no /_next/image, .nojekyll handled by .github/workflows/deploy.yml, the fonts (Dela Gothic One + Zen Kaku Gothic New via next/font: are CJK subsets preloaded unnecessarily? what is the total font transfer for the ES page?). Weight: total transfer of the page, LCP image priority, lazy loading of the gallery. Also check the live deploy if it is up: https://slonikonclaude.github.io/tairyo-kaiten-sushi/ (curl status, then screenshot with shoot.mjs PORT=9624). Report defects only.`,
  },
]

const FINDINGS = {
  type: 'object',
  properties: {
    findings: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          file: { type: 'string' },
          line: { type: 'string' },
          severity: { type: 'string', enum: ['high', 'medium', 'low'] },
          evidence: { type: 'string' },
          fix: { type: 'string' },
        },
        required: ['title', 'file', 'line', 'severity', 'evidence', 'fix'],
      },
    },
  },
  required: ['findings'],
}

const VERDICT = {
  type: 'object',
  properties: { real: { type: 'boolean' }, reason: { type: 'string' }, better_fix: { type: 'string' } },
  required: ['real', 'reason', 'better_fix'],
}

const verifyPrompt = (f, dim, n) => `You are skeptic #${n} checking one finding from a pre-publish review (dimension: ${dim}) of the Tairyo Kaiten Sushi website at ${ROOT} (read ${ROOT}/DESIGN.md for deliberate decisions). Try to REFUTE it: open the cited file/line, reproduce with the sources in ${ROOT}/_data or a screenshot (cd ${ROOT}/_data/scripts && PORT=${9630 + n} node shoot.mjs ${URL_ES} <width> ${ROOT}/_data/crops/skeptic-${dim}-${n}), compute contrast yourself, etc. It is real only if the defect actually exists in the current code/output AND matters to users, correctness or the deploy. If DESIGN.md deliberately decided it, it is not real. Do not edit project files.

Finding: ${JSON.stringify(f)}

Return real (true/false), the reason with the evidence you checked, and a better fix if the proposed one is wrong or incomplete (empty string otherwise).`

const results = await pipeline(
  DIMENSIONS,
  (d) => agent(d.prompt, { label: `review:${d.key}`, phase: 'Review', schema: FINDINGS }),
  (review, d) => {
    if (!review) return []
    return parallel(review.findings.map((f) => () =>
      parallel([1, 2].map((n) => () => agent(verifyPrompt(f, d.key, n), { label: `verify:${d.key}:${f.title.slice(0, 30)}#${n}`, phase: 'Verify', schema: VERDICT })))
        .then((vs) => ({ dim: d.key, ...f, verdicts: vs.filter(Boolean), votes: vs.filter(Boolean).filter((v) => v.real).length }))
    ))
  },
)
const all = results.filter(Boolean).flat()
const confirmed = all.filter((f) => f.votes >= 1)
log(`${all.length} findings, ${all.filter((f) => f.votes === 2).length} confirmed by both skeptics, ${all.filter((f) => f.votes === 1).length} split`)
return { confirmed, rejected: all.filter((f) => f.votes === 0).map((f) => ({ dim: f.dim, title: f.title, why: f.verdicts.map((v) => v.reason) })) }
